-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 23:47:09 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_treslagunas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_treslagunas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_treslagunas` ;

-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Usuario` (
  `idNombre` SMALLINT NOT NULL AUTO_INCREMENT,
  `sexo` TINYINT(1) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `lugarOrigen` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `idioma` TINYINT(1) NULL,
  `tipoUsuario` TINYINT(1) NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idNombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Cabañas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Cabañas` (
  `idCabana` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(700) NULL,
  `maxPersonas` SMALLINT NULL,
  `tarifa` SMALLINT NULL,
  `personaExtra` SMALLINT NULL,
  PRIMARY KEY (`idCabana`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Reservacion` (
  `idReservacion` SMALLINT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATETIME NULL,
  `fechaFinal` DATETIME NULL,
  `noPersonas` SMALLINT NULL,
  `fotoPago` VARCHAR(45) NULL,
  `Usuario_idNombre` SMALLINT NOT NULL,
  `estado` SMALLINT NULL,
  PRIMARY KEY (`idReservacion`, `Usuario_idNombre`),
  INDEX `fk_Reservacion_Usuario1_idx` (`Usuario_idNombre` ASC),
  CONSTRAINT `fk_Reservacion_Usuario1`
    FOREIGN KEY (`Usuario_idNombre`)
    REFERENCES `bd_treslagunas`.`Usuario` (`idNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Actividades` (
  `idActividad` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tarifa` SMALLINT NULL,
  `descripcion` VARCHAR(700) NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Reservacion_has_Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Reservacion_has_Actividades` (
  `Reservacion_idReservacion` SMALLINT NOT NULL,
  `Actividades_idActividad` SMALLINT NOT NULL,
  PRIMARY KEY (`Reservacion_idReservacion`, `Actividades_idActividad`),
  INDEX `fk_Reservacion_has_Actividades_Actividades1_idx` (`Actividades_idActividad` ASC),
  INDEX `fk_Reservacion_has_Actividades_Reservacion_idx` (`Reservacion_idReservacion` ASC),
  CONSTRAINT `fk_Reservacion_has_Actividades_Reservacion`
    FOREIGN KEY (`Reservacion_idReservacion`)
    REFERENCES `bd_treslagunas`.`Reservacion` (`idReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_has_Actividades_Actividades1`
    FOREIGN KEY (`Actividades_idActividad`)
    REFERENCES `bd_treslagunas`.`Actividades` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_treslagunas`.`Reservacion_has_Cabañas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_treslagunas`.`Reservacion_has_Cabañas` (
  `Reservacion_idReservacion` SMALLINT NOT NULL,
  `Cabañas_idCabana` SMALLINT NOT NULL,
  PRIMARY KEY (`Reservacion_idReservacion`, `Cabañas_idCabana`),
  INDEX `fk_Reservacion_has_Cabañas_Cabañas1_idx` (`Cabañas_idCabana` ASC),
  INDEX `fk_Reservacion_has_Cabañas_Reservacion1_idx` (`Reservacion_idReservacion` ASC),
  CONSTRAINT `fk_Reservacion_has_Cabañas_Reservacion1`
    FOREIGN KEY (`Reservacion_idReservacion`)
    REFERENCES `bd_treslagunas`.`Reservacion` (`idReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_has_Cabañas_Cabañas1`
    FOREIGN KEY (`Cabañas_idCabana`)
    REFERENCES `bd_treslagunas`.`Cabañas` (`idCabana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
